# Generated by Django 3.0.5 on 2020-04-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_userinfo_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="title",),
    ]
