# Generated by Django 3.0.5 on 2020-04-24 11:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_remove_userinfo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
