# Generated by Django 3.0.5 on 2020-04-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_responcibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='resume.Project')),
            ],
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='discription',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='Responcibility',
        ),
    ]
